### ISSUE TITLE
set-cogfx option

### ISSUE THREAD

**Issue by avxkim** [KyleGospo/Steam-Deck-Software-Undervolt#4]
Hi! what a great tool! I got a question regards a file `set-ryzenadj-tweaks.sh`. 
Do i need to uncomment this line: `--set-cogfx=0xFFFFB` ? Seems like GPU is being supported?

**Comment by KyleGospo** [comment]
Ryzenadj doesn't suppport that option on VanGogh, it's there just in case that's ever fixed.
